### ISSUE TITLE
does not work in next js

### ISSUE THREAD

**Issue by Muriloflimaa** [vadymshymko/react-simply-carousel#63]
![image](https://user-images.githubusercontent.com/103587328/201343896-d45ddc70-ce38-4729-a1e4-44593f167734.png)

return error TypeError: Cannot read properties of undefined (reading 'offsetWidth') next js

**Comment by vadymshymko** [comment]
Hello @Muriloflimaa. Please, provide information about which version of react-simple-carousel and next J's you are using. if you are using a non-8.x.x version of react-simply-carousel, please, try using the latest version

**Comment by Muriloflimaa** [comment]
"react-simply-carousel": "^8.4.1",

**Comment by vadymshymko** [comment]
@Muriloflimaa, thanks for the information provided. I just launched nextjs with react-simply-carousel imported by next/dynamic and found no issues. Perhaps your problem is related to the fact that you are using an empty React.Fragment as a slide or something else that is not a dom element. The source code of the page or component inside which react-simply-carousel is used will help to more accurately assess the situation.
